#!/bin/bash

FSNAP_CONFDIR=${FSNAP_CONFDIR:-/etc/fsnap}

if [ ! -d "$FSNAP_CONFDIR" ]; then
    exit
fi

date=$(date +%Y-%m-%d_%H%M%S)

fatal() {
    exit 1
}
trap fatal INT TERM

for conf in $FSNAP_CONFDIR/*.conf; do
    [ ! -r $conf ] && continue

    (
    source $conf

    if [ ! -d "$BACKUPDIR" ]; then
        mkdir -pv $BACKUPDIR
    fi

    sync
    for vol in "${VOLS[@]}"; do
        (
        # Keep $howmuch snapshots. If no howmuch_* config variable defined for
        # a volume, assume 5.

        eval howmuch=\${howmuch_$vol:-5}

        if [ "$howmuch" -gt 0 ]; then
            files=$(ls -d "$BACKUPDIR/$vol"* 2>/dev/null | \
                head -n -$((howmuch - 1)))
            [ -n "$files" ] && btrfs sub del $files
        fi

        declare -i max=5 i=0
        while ! btrfs sub snap -r "$ROOTVOL/$vol" "$BACKUPDIR/$vol.$date"; do
            ((++i))
            echo "$vol: Try $i of $max" >&2
            if [ $i = $max ]; then
                echo "Giving up." >&2
                break
            fi
            sleep 2
        done
        ) &
    done
    wait
    ) &
done
wait
