#!/bin/bash

FSNAP_CONFDIR=${FSNAP_CONFDIR:-/etc/fsnap}

if [ ! -d "$FSNAP_CONFDIR" ]; then
    exit
fi

date=$(date +%Y-%m-%d_%H%M%S)

fatal() {
    exit 1
}
trap fatal INT TERM

for conf in $FSNAP_CONFDIR/*.conf; do
    [ ! -r $conf ] && continue

    (
    source $conf

    if [ ! -d "$BACKUPDIR" ]; then
        mkdir -pv $BACKUPDIR
    fi

    sync
    for vol in "${VOLS[@]}"; do
        (
        # Replace directory separators (/) with underscores (_). This is used
        # in the howmuch_* variables (see below) since variables must not
        # contain slashes, as well as the snapshot name, to avoid nesting
        # snapshots. To further avoid bash variable conflicts, replace dots
        # and dashes with underscores, too.
        newvol=${vol//[\/.-]/_}

        # If a variable $delete_if exists and is set to a predicate, then the
        # extraneous snapshots are deleted only if $delete_if evaluates to
        # true. An empty variable lets eval always be true.

        if eval $delete_if; then
            # Keep $howmuch snapshots. If no howmuch_* config variable defined
            # for a volume, assume 5.

            eval howmuch=\${howmuch_$newvol:-5}

            if [ "$howmuch" -gt 0 ]; then
                files=$(ls -d "$BACKUPDIR/$newvol".* 2>/dev/null | \
                    head -n -$((howmuch - 1)))
                [ -n "$files" ] && btrfs sub del $files
            fi
        fi

        declare -i max=5 i=0
        while ! btrfs sub snap -r "$ROOTVOL/$vol" "$BACKUPDIR/$newvol.$date"
        do
            ((++i))
            echo "$vol: Try $i of $max" >&2
            if [ $i = $max ]; then
                echo "Giving up." >&2
                break
            fi
            sleep 2
        done
        ) &
    done
    wait
    ) &
done
wait
